title: "Wasatch-Archaeo"
author: "Jaydee Dolinar, Environmental Archaeologist, Ph.D.-M.S.c, © 2025. All rights reserved."
description: "Bridging the Cultural–Ecological Divide Through Prehistoric Adaptive Lifeways" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "jd.louis.wy@gmail.com"
github_username: "jd657824"
bluesky_username: "@jd657824"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
# The top part stays the same as your current config
url: "https://jd657824.github.io"
baseurl: "/wasatch_archaeo.github.io"
theme: "minima"
minima:
  skin: null
  social_links:
    github: yourusername
    linkedin: yourusername
    bluesky: yourusername
# The rest of your config stays the same

header_pages:
  - about.md
  - projects.md
  - blog.md
  - credentials.md
  - podcast.md

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

feed:
  path: "feed.xml"

titles_from_headings:
  strip_title: true
  collections: true

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
    type: post
    values:
      tags: Other

  - scope:
      path: "feed.xml"
    values:
      layout: "feed"
