title: "Wasatch Archaeobotanical"
author: "Jaydee Dolinar, Environmental Archaeologist, Ph.D."
description: "Bridging the Cultural–Ecological Divide Through Prehistoric Adaptive Lifeways: A Geoarchaeological, Archaeobotanical, and Geocomputational Approach to Environmental Resilience and Sustainability." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "jd.louis.wy@gmail.com"
github_username: "jd657824"
bluesky_username: "@jd657824"
#facebook_username: username
#flickr_username: username
instagram_username: "@jd657824"
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"
rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-archives
  - jekyll-mentions

titles_from_headings:
  strip_title: true
  collections: true

# This line ensures your posts use /YYYY/MM/DD/title/ URLs:
permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
